### ISSUE TITLE
Stack proposition

### ISSUE THREAD

**Issue by ghost** [moggers87/biggit#1]
For quiet sometime, 2 years in one month exactly, I will be working on my ideal free software stack, all written in Python except the database for now. Here is it:

- Database: Graph database: [GraphitiDB](https://github.com/python-graph-lovestory/Java-GraphitiDB)
- Complex volatile data: [Memo](https://github.com/amirouche/Memo) a redis-like database
- Frontend: [Pythonium](https://github.com/pythonium/pythonium) Python->Javascript translator
- Backend: [Nerfed](https://github.com/amirouche/Nerfed) Application framework

Nerfed just need to be updated to work with websockets, see this series of article about the subject (PythonJS is the old version of Pythonium):

- [Python 3, websockets and PythonJS (1)](http://hypermove.net/notes/2013/suprm-python-3-websockets-and-pythonjs/index.html)
- [Python 3, websockets and PythonJS (2)](http://hypermove.net/notes/2013/suprm-python-3-websockets-and-pythonjs-2/index.html)
- [Python 3, websockets and Circus](http://hypermove.net/notes/2013/suprm-python-3-websockets-and-circus/index.html)

So when Nerfed will be ready it will be both possible to do realtime and non-realtime with the same framework. A thing that is not possible today and inefficient. To be sure of that, I did [some experiments with socket.io and Django](https://github.com/amirouche/hivi.mx) and it doesn't work. Ask me if you are not convinced. This is pervasive in current Python framework, because they weren't made to work realtime. Whereas Nerfed upgrades gracefully to work with realtime because:

- at the core, it doesn't make assumptions about the kind of application you are builiding. It's just a framework for building application as a set of subapplication. Even if the current code reflect that it's build for the web. It can be adapted to work in other situation, like the realtime web.
- It doesn't make any assumptions regarding what you will do with your data wrappers. Django has forms and models, Flask has nothing but follow the same path basicly. In Nerfed you have the ```Imperator``` which holds data can validate them, execute actions and that is all. Form rendering is another topic so another object. But you can use the same ```Imperator``` instance for both validation, rendering, storing and serialization. At the core ```Imperator``` class is just a data wrapper with metadatas.

All projects are more or less documented, ask me any questions if you have a doubt.

Are you interested to work using this stack?

**Comment by moggers87** [comment]
Closing because this project is just an idea I had in my head, nothing else.
